var ZoneDetails = {
  "ClawZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "ClawZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "ClawZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FangZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "KiriRuinsZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "IslandZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "IslandZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "VolcanoZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "LightningZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "LightningZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "LightningZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "LightningZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "LightningZone06":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "BearZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "RainZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "RainZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "RainZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone06":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone07":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FireZone08":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "TideZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "FlowerZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "TeaZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "TeaZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SnowZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SnowZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SnowZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SnowZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SnowZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "MoonZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WaterfallZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WaterfallZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "GrassZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone06":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "EarthZone07":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "ForestZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "ForestZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "ShadowZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "SwampZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "TornadoZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "BirdZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "StoneZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "IronZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "RiverZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "RiverZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone06":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone07":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "WindZone08":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone01":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone02":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone03":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone04":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone05":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone06":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  },
  "HavenZone07":{
     "name":"",
     "blurb":"",
     "detail":"",
     "owner":""
  }
}

if (typeof window !== 'undefined') {
  window.ZoneDetails = ZoneDetails
} else {
  module.exports = ZoneDetails
}
