var ZoneDetails = {
   "ClawZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone11":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone12":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone13":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone14":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ClawZone15":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FangZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "KiriRuinsZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "KiriRuinsZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IslandZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "VolcanoZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "VolcanoZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "VolcanoZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "LightningZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "LightningZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "LightningZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "LightningZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "LightningZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "BearZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RainZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RainZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RainZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone11":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone12":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone13":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone14":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FireZone15":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TideZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FlowerZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "FlowerZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TeaZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TeaZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TeaZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SnowZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SnowZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SnowZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SnowZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SnowZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "MoonZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "MoonZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WaterfallZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WaterfallZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WaterfallZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "GrassZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "GrassZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "EarthZone11":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ForestZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ForestZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ShadowZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "ShadowZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "SwampZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TornadoZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TornadoZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "TornadoZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "BirdZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "StoneZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "StoneZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "StoneZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IronZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IronZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "IronZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RiverZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RiverZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RiverZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RiverZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "RiverZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   'WindZone01': {
     name: 'The Grand Desert',                        //Zone name
     blurb: 'A fucking huge desert.',                 //Short details
     detail: 'Seriously. It\'s really fucking big.',  //Longer details
     owner: 'Wind Daimyou'                            //Owning Faction
   },
   'WindZone02': {
     name: '',
     blurb: '',
     detail: '',
     owner: ''
   },
   'WindZone03': {
     name: 'Sunagakure',
     blurb: 'It\'s the sand village.',
     detail: 'Gaara lived here once. Probably.',
     owner: 'Sunagakure'
   },
   'WindZone04': {
     name: 'The Pristine Oasis',
     blurb: 'Short text.',
     detail: 'Much longer text.',
     owner: 'Wind Daimyou'
   },
   "WindZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "WindZone11":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone01":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone02":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone03":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone04":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone05":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone06":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone07":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone08":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone09":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone10":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   },
   "HavenZone11":{
      "name":"",
      "blurb":"",
      "detail":"",
      "owner":""
   }
}

if (typeof window !== 'undefined') {
  window.ZoneDetails = ZoneDetails
} else {
  module.exports = ZoneDetails
}
